# Generated by Django 2.2.3 on 2019-07-06 07:58

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20190706_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 7, 58, 54, 847811)),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Adventure', 'Adventure'), ('Food', 'Food'), ('Tech', 'Tech'), ('Family', 'Family'), ('Health', 'Health'), ('Sports', 'Sports'), ('Film', 'Film'), ('Books', 'Books'), ('Dance', 'Dance'), ('Arts', 'Arts')], max_length=62),
        ),
    ]
