# Generated by Django 2.2.3 on 2019-07-06 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_auto_20190706_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 9, 38, 9, 665819)),
        ),
    ]
