# Generated by Django 2.2.3 on 2019-07-06 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_auto_20190706_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(default='media/adventure.jpeg', upload_to='group_photos'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 10, 44, 20, 108814)),
        ),
    ]
