# Generated by Django 2.2.3 on 2019-07-06 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_auto_20190706_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(default='adventure.jpeg', upload_to='group_photos'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 11, 45, 7, 393721)),
        ),
    ]
