# Generated by Django 2.2.3 on 2019-07-09 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0008_auto_20190709_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 10, 16, 14, 981513)),
        ),
    ]
