# Generated by Django 2.2.3 on 2019-07-09 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0009_auto_20190709_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 10, 17, 30, 553935)),
        ),
    ]
