# Generated by Django 2.2.3 on 2019-07-10 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0010_auto_20190709_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='photo',
            field=models.ImageField(null=True, upload_to='group_photos'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 6, 30, 5, 338554)),
        ),
    ]
