# Generated by Django 2.2.3 on 2019-07-10 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0011_auto_20190710_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 9, 15, 52, 433405)),
        ),
    ]
