# Generated by Django 2.2.3 on 2019-07-10 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0012_auto_20190710_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 9, 18, 47, 571041)),
        ),
    ]
