# Generated by Django 2.2.3 on 2019-07-10 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0015_auto_20190710_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='photo',
            field=models.ImageField(default='group_photos/film.jpg', upload_to='group_photos'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 10, 12, 9, 935493)),
        ),
    ]
