# Generated by Django 2.2.3 on 2019-07-10 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0017_auto_20190710_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 17, 16, 52, 392607)),
        ),
    ]
