# Generated by Django 2.2.3 on 2019-07-11 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0018_auto_20190710_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='slots',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 5, 10, 41, 998831)),
        ),
    ]
